# Generated by Django 5.2.17 on 2026-08-12 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsDailySnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True, unique=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("recommendation", models.JSONField(blank=True, default=dict)),
                ("users", models.JSONField(blank=True, default=dict)),
                ("ml", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "analytics_daily_snapshots",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationServeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("algorithm", models.CharField(db_index=True, max_length=64)),
                (
                    "model_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True, db_index=True, default="api", max_length=64
                    ),
                ),
                ("cached", models.BooleanField(db_index=True, default=False)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("movie_ids", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("served_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_serves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recommendation_serve_events",
                "ordering": ["-served_at"],
                "indexes": [
                    models.Index(
                        fields=["algorithm", "-served_at"], name="serve_algo_served_idx"
                    ),
                    models.Index(
                        fields=["cached", "-served_at"], name="serve_cached_served_idx"
                    ),
                ],
            },
        ),
    ]
