# Generated by Django 5.2.17 on 2026-08-12 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_analytics_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recommendationserveevent",
            index=models.Index(
                fields=["surface", "-served_at"], name="serve_surface_served_idx"
            ),
        ),
    ]
