# Generated by Django 5.2.17 on 2026-08-12 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoviePopularityScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.FloatField(db_index=True)),
                ("signals", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(db_index=True)),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity_score",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "movie_popularity_scores",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="MovieTrendingScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("window_hours", models.PositiveIntegerField(db_index=True)),
                ("score", models.FloatField(db_index=True)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("computed_at", models.DateTimeField(db_index=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trending_scores",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "movie_trending_scores",
                "ordering": ["-score"],
                "indexes": [
                    models.Index(
                        fields=["window_hours", "-score"],
                        name="trending_window_score_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("movie", "window_hours"),
                        name="trending_scores_movie_window_unique",
                    )
                ],
            },
        ),
    ]
