# Generated by Django 5.2.17 on 2026-08-12 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborativeModelArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("artifact_path", models.CharField(max_length=512)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("user_count", models.PositiveIntegerField(default=0)),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("interaction_count", models.PositiveIntegerField(default=0)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("hyperparameters", models.JSONField(blank=True, default=dict)),
                ("trained_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "collaborative_model_artifacts",
                "ordering": ["-trained_at"],
            },
        ),
    ]
