# Generated by Django 5.2.17 on 2026-08-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0003_recommendation_evaluation_report"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collaborativemodelartifact",
            index=models.Index(
                fields=["is_active", "-trained_at"],
                name="cf_artifact_active_trained_idx",
            ),
        ),
    ]
