# Generated by Django 5.2.17 on 2026-08-12 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("preferred_languages", models.JSONField(blank=True, default=list)),
                ("preferred_decades", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "user preference",
                "verbose_name_plural": "user preferences",
                "db_table": "user_preferences",
            },
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="language",
            new_name="preferred_language",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_primary",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["user", "is_primary"], name="profiles_user_primary_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user",),
                name="profiles_one_primary_per_user",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="favorite_actors",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_by_users", to="movies.actor"
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="favorite_directors",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_by_users", to="movies.director"
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="favorite_genres",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_by_users", to="movies.genre"
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
