# Generated by Django 5.2.17 on 2026-08-12 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
        ("movies", "0002_movie_keywords"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movieinteraction",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="interactions_event_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="movieinteraction",
            index=models.Index(
                fields=["movie", "event_type"], name="interactions_movie_event_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchhistory",
            index=models.Index(
                fields=["completed_at"], name="watch_hist_completed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchhistory",
            index=models.Index(
                fields=["user", "completed_at"], name="watch_hist_user_comp_idx"
            ),
        ),
    ]
