# Generated by Django 5.2.17 on 2026-08-12 14:50

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_enable_pgvector"),
        ("movies", "0002_movie_keywords"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                ("model_name", models.CharField(db_index=True, max_length=128)),
                ("model_version", models.CharField(db_index=True, max_length=64)),
                ("embedding_dimension", models.PositiveIntegerField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "movie_embeddings",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "model_version"],
                        name="movie_embeddings_model_idx",
                    ),
                    pgvector.django.indexes.HnswIndex(
                        django.contrib.postgres.indexes.OpClass(
                            "embedding", name="vector_cosine_ops"
                        ),
                        ef_construction=64,
                        m=16,
                        name="movie_embed_hnsw_cosine_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("movie", "model_name", "model_version"),
                        name="movie_embeddings_movie_model_unique",
                    )
                ],
            },
        ),
    ]
