# Generated by Django 5.2.17 on 2026-08-12 13:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "db_table": "actors",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="actors_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "db_table": "directors",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="directors_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={
                "db_table": "genres",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["slug"], name="genres_slug_idx")],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("original_title", models.CharField(blank=True, max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("tagline", models.CharField(blank=True, max_length=500)),
                (
                    "release_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("runtime", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, default="en", max_length=10)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("popularity", models.FloatField(db_index=True, default=0.0)),
                (
                    "vote_average",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("poster_url", models.URLField(blank=True, max_length=500)),
                ("backdrop_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rumoured", "Rumoured"),
                            ("planned", "Planned"),
                            ("in_production", "In Production"),
                            ("post_production", "Post Production"),
                            ("released", "Released"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="released",
                        max_length=20,
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
            ],
            options={
                "db_table": "movies",
                "ordering": ["-popularity", "title"],
                "indexes": [
                    models.Index(
                        fields=["-popularity", "title"],
                        name="movies_popularity_title_idx",
                    ),
                    models.Index(
                        fields=["release_date", "-vote_average"],
                        name="movies_date_rating_idx",
                    ),
                    models.Index(
                        fields=["status", "-popularity"],
                        name="movies_status_popularity_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="movies_search_vector_gin"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("vote_average__gte", 0.0), ("vote_average__lte", 10.0)
                        ),
                        name="movies_vote_average_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("vote_count__gte", 0)),
                        name="movies_vote_count_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MovieActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(blank=True, max_length=255)),
                ("billing_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_actors",
                        to="movies.actor",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_actors",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "movie_actors",
                "ordering": ["billing_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["actor", "movie"], name="movie_actors_actor_movie_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("movie", "actor"), name="movie_actors_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MovieDirector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_directors",
                        to="movies.director",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_directors",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "movie_directors",
                "indexes": [
                    models.Index(
                        fields=["director", "movie"],
                        name="movie_directors_dir_movie_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("movie", "director"), name="movie_directors_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MovieGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_genres",
                        to="movies.genre",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_genres",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "movie_genres",
                "indexes": [
                    models.Index(
                        fields=["genre", "movie"], name="movie_genres_genre_movie_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("movie", "genre"), name="movie_genres_unique"
                    )
                ],
            },
        ),
    ]
