# Generated by Django 5.2.17 on 2026-08-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="keywords",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
